engines:
  bandit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python:
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  pylint:
    enabled: true
    channel: "beta"
  radon:
    enabled: true
  sonar-python:
    enabled: true
