version = 1

test_patterns = [
    "tests/*.py"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["poetry.lock"]

[analyzers.meta]
runtime_version = "3.x.x"
type_checker = "mypy"
