repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: flake8
        args: [--max-line-length=88, --ignore=F401]
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
