dist: xenial
language: python

branches:
  only:
    - master

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry
    - $HOME/.cache/pre-commit

stages:
  - check
  - test
  - name: deploy
    if: tag IS present

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

before_install:
  - pip install --upgrade pip
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install:
  - poetry install

script: pytest tests/ --cov=jekyllnb

jobs:
  include:
    - stage: check
      name: Safety
      python: 3.6
      install: pip install safety
      script:
        - poetry show -a
        - poetry show -a | wc -l
        - poetry show -a | sed 's/(!)//' | awk '{print $1,"==",$2}' | safety check --stdin
      after_success: skip

    - name: Linting
      python: 3.7
      before_install: skip
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script: pre-commit run --all-files
      after_success: skip

    - stage: deploy
      name: PyPI
      python: 3.6
      install: skip
      script: skip
      after_success: skip
      before_deploy: poetry build
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          tags: true
