language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - pytest --cov=jekyllnb --cov-report=xml
after_success:
  - codecov
  - python-codacy-coverage -r coverage.xml
before_deploy:
  - poetry build
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    tags: true
