environment:
  matrix:
    - PYTHON: "C:/Python27-x64"
      PYTHON_VERSION: "2.7"

    - PYTHON: "C:/Python34-x64"
      PYTHON_VERSION: "3.4"

    - PYTHON: "C:/Python35-x64"
      PYTHON_VERSION: "3.5"

    - PYTHON: "C:/Python36-x64"
      PYTHON_VERSION: "3.6"

    - PYTHON: "C:/Python37-x64"
      PYTHON_VERSION: "3.7"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install poetry"
  - "poetry install"
  - "if [[ $PYTHON_VERSION == 2.7 ]]; then pip install more-itertools==5.0.0; fi"

test_script:
  - "pytest tests/ --cov=jekyllnb"
