build: false

branches:
  only:
    - master

cache:
  - '%LOCALAPPDATA%\pip\Cache'
  - '%LOCALAPPDATA%\pypoetry\Cache'

environment:
  matrix:
    - TOXENV: py27
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37

init:
  - 'SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%'
  - python --version

install:
  - python -m pip install --upgrade pip
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - 'SET PATH=%USERPROFILE%\.poetry\bin;%PATH%'
  - pip install tox

test_script:
  - tox -- -m "not unix"
