environment:
  matrix:
    - PYTHON: "C:/Python27-x64"
      PYTHON_VERSION: "2.7"

    - PYTHON: "C:/Python35-x64"
      PYTHON_VERSION: "3.5"

    - PYTHON: "C:/Python36-x64"
      PYTHON_VERSION: "3.6"

    - PYTHON: "C:/Python37-x64"
      PYTHON_VERSION: "3.7"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -m pip install --upgrade pip"
  - "pip install poetry"
  - "IF %PYTHON_VERSION%==2.7 (poetry install -vv -E more-itertools=5.0.0) ELSE (poetry install -vv)"

build: false

test_script:
  - "poetry run pytest tests/ --cov=jekyllnb"
