build: false

cache:
  - '%LOCALAPPDATA%\pip\Cache'
  - '%LOCALAPPDATA%\pypoetry\Cache'

environment:
  matrix:
    - PYTHON: "C:/Python27-x64"
    - PYTHON: "C:/Python35-x64"
    - PYTHON: "C:/Python36-x64"
    - PYTHON: "C:/Python37-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -m pip install --upgrade pip"
  - "pip install poetry"
  - "poetry install -vv"

test_script:
  - "poetry run pytest tests/ --cov=jekyllnb"
