site_name: JekyllNB
site_description: Convert Jupyter Notebooks to Jekyll-ready Markdown
site_author: Kevin Lane

repo_url: https://github.com/klane/jekyllnb

theme: readthedocs
extra_css: [css/toc.css]

nav:
  - Overview: index.md
  - Usage:
      - Site Layout: layout.md
      - Multiple Notebooks: multiple-notebooks.md
      - nbconvert: nbconvert.md
  - About:
      - Release Notes: changelog.md
      - License: license.md
