[tool.poetry]
name = "jekyllnb"
version = "0.1.0"
description = "Convert Jupyter Notebooks to Jekyll-ready Markdown files"
authors = ["Kevin Lane <lane.kevin.a@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/klane/jekyllnb"

[tool.poetry.dependencies]
python = "~2.7 || ^3.4"
click = "^7.0"
nbconvert = "^5.4"

[tool.poetry.dev-dependencies]
pytest = "^3.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
